config/routes.rb
Dynamo::Application.routes.draw do
  resources :pages do
	collection do
		get "find"
	end
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
  def parse_syntax included=false
    data = self.content
    data.gsub!(/\{!\s*(.+?)\s*\}\n*/xm,"")
    data.gsub!(/\{#\s*(.+)\s*\}\n*/) do |m|
      c = Page.where('title LIKE ?', m[2...m.length-1]).first
      if c
        c.parse_syntax true
      else
        "INVALID INCLUDE - #{m}"
      end
    end

    data.gsub!(/\{%\s*(.+?):(.+?)\s*\}\n*/xm,"<%= link_to('\\1', find_pages_path(:name => '\\2')) %>")
    data.gsub!(/\{%\s*(.+?)\s*\}\n*/xm,"<%= link_to('\\1', find_pages_path(:name => '\\1')) %>")
    data.gsub!(/\{=\s*(.+?)\s*\}\n*/xm,"<%= \\1 %>")
    if included
      data.gsub!(/\{-\s*(.+?)\s*\}\n*/xm,"")
      data.gsub!(/\{&\s*(.+?)\s*\}\n*/xm,"\\1")
    else
      data.gsub!(/\{-\s*(.+?)\s*\}\n*/xm,"\\1")
      data.gsub!(/\{&\s*(.+?)\s*\}\n*/xm,"")
    end
    
    data.gsub!(/\s*\{\s*(.+?)\s*\}\n*/xm,"<% \\1 %>")
    data
  end

  def unparsed
    self.content
  end

  def embedded_data
    data = []
    if self.content.match /\{!\s*(.+?)\s*\}\n*/xm
      self.content.gsub(/\{!\s*(.+?)\s*\}\n*/xm) do |m|
        data << m
        m
      end
      data
    else
     [] 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	include ApplicationHelper
	# GET /pages
	# GET /pages.json
	def index
		@pages = Page.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @pages }
		end
	end

	# GET /pages/1
	# GET /pages/1.json
	def show
		@page = Page.find(params[:id])
		
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @page }
		end
	end

	# GET /pages/new
	# GET /pages/new.json
	def new
		@page = Page.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @page }
		end
	end

	# GET /pages/1/edit
	def edit
		@page = Page.find(params[:id])
	end

	# POST /pages
	# POST /pages.json
	def create
		@page = Page.new(params[:page])

		respond_to do |format|
			if @page.save
				format.html { redirect_to @page, notice: 'Page was successfully created.' }
				format.json { render json: @page, status: :created, location: @page }
			else
				format.html { render action: "new" }
				format.json { render json: @page.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /pages/1
	# PUT /pages/1.json
	def update
		@page = Page.find(params[:id])

		respond_to do |format|
			if @page.update_attributes(params[:page])
				format.html { redirect_to @page, notice: 'Page was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @page.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /pages/1
	# DELETE /pages/1.json
	def destroy
		@page = Page.find(params[:id])
		@page.destroy

		respond_to do |format|
			format.html { redirect_to root_url }
			format.json { head :no_content }
		end
	end

	def find
		@pages = Page.where('title LIKE ?', params[:name])

		if @pages.count == 1
			@page = @pages.first
			render :show
		elsif @pages.count == 0
			redirect_to new_page_path(:name => params[:name]), notice:  'Couldn\'t find that page.  Would you like to start it?'
		else
			render :index
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	  redirect_to Page.where(:title => "Welcome").first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def tabify list
		r = '<ul class="nav nav-tabs">'
		active = true
		list.each_pair do |li, str|
			if content_for? li
				r << "
				"
				if active
					r << '<li class="active"><a data-toggle="tab" href="#'+li.to_s+'">'+str+'</a></li>'
					active = false
				else
					r << '<li><a data-toggle="tab" href="#'+li.to_s+'">'+str+'</a></li>'
				end
			end
		end
		r << '</ul>'
		r << "

		"
		r << '<div class="tab-content" style="border: thin inset black; margin-top: 0px; background-color: #fff; padding: 5px;">'
		list.each_pair do |li, str|
			if content_for? li
				if !active
					r << '<div class="tab-pane active" id="'+li.to_s+'">'
					active = true
				else
					r << '<div class="tab-pane" id="'+li.to_s+'">'
				end
				r << "
				"
				r << content_for(li)
				r << "
				"
				r << '</div>'
				r << "
				"
			end
		end
		r << '</div>'
		r.html_safe
	end

	def twitterized_type(type)
		case type
		when :alert
			"warning"
		when :error
			"error"
		when :notice
			"info"
		when :success
			"success"
		else
			type.to_s
		end
	end

	def time_delta time
		if time < Time.now
			distance_of_time_in_words_to_now(time) + " ago"
		else
			distance_of_time_in_words_to_now(time) + " from now"
		end
	end

	def truthy_thumb(value)
		if value=="*"
			i('star').html_safe
		elsif value
			i('thumbs-up').html_safe
		else
			i('thumbs-down').html_safe
		end
	end

	def i(c)
		('<i class="icon-' + c + ' icon-white"></i>').html_safe
	end

  def link_to_page x, n=nil
    link_to( (n ? n : x), find_pages_path(:name => x))
  end

  def btn x, url, c=nil
    link_to x, url, :class => (c ? "btn btn-#{c}": 'btn' )
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamo!</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body style="padding-top: 60px;">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Dynamo!</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Add a New Page", new_page_path %></li>
              <li><%= link_to "All Pages", pages_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12">
            <% flash.each do |typ,msg| %>
              <div class="alert alert-<%= twitterized_type typ %>" id="notice"><a class="close" data-dismiss="alert" href="#"><%=i 'remove' %></a><%= msg %></div>
            <% end %>
            <%= yield %>
          </div>
        </div><!--/row-->
      </div><!--/content-->
    </div> <!-- /container -->
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Editing <%= @page.title %></h1>

<%= bootstrap_form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_area :content, size: "80x10", label: "Page Content" %>
  <%= f.actions do %>
	  <%= f.primary 'Submit' %>
  <% end %>
<% end %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table table-striped table-bordered">
<% @pages.in_groups_of(5) do |group| %>
  <tr>
	  <% group.each do |page| %>
		<td width="20%"><%= page ? link_to(page.title, page) : "" %></td>
	  <% end %>
  </tr>
<% end %>
</table>

app/views/pages/new.html.erb
<h1>Create a New page</h1>

<%= bootstrap_form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title, :value => params[:name] %>
  <%= f.text_area :content, size: "80x10", label: "Page Content" %>
  <%= f.actions do %>
	  <%= f.primary 'Submit' %>
  <% end %>
<% end %>

app/views/pages/show.html.erb
<%
  @data = RedCloth.new(\
    ERB.new(@page.parse_syntax, nil, "<>").result(binding))\
    .to_html
%>

<%# @data = "<pre>" + @page.parse_syntax + "</pre>" %>


<div class="page-header"><h1><%= @page.title %></div>

  <div class="well"><%= @data.html_safe %></div>

  <div class="form-actions">
    <%= link_to 'Edit Page', edit_page_path(@page), :class => 'btn btn-mini btn-inverse' %>
    <%= link_to 'Remove Page', @page, :method => :delete, :class => 'btn btn-mini btn-danger' %>
  </div>

app/views/welcome/index.html.erb
<div class="page-header"><h1>Welcome!</h1></div>